site_name: TechTransThai Docs
site_url: https://docs.techtransthai.org
repo_url: https://forge.techtransthai.org/techtransthai/docs.techtransthai.org
edit_uri: 'src/branch/main/docs/'

site_description: TechTransThai Docs - our knowledge base for everything
site_author: TechTransThai Community
theme:
  name: readthedocs
nav:
  - หน้าแรก: index.md
  - การเพิ่มข้อมูลลงใน OpenStreetMap: osm-contrib.md