site_name: Wonderful Mobile Docs
site_url: https://wonderful-mobile-docs.techtransthai.org
repo_url: https://forge.techtransthai.org/wonderful-mobile/docs
edit_uri: 'src/branch/main/docs/'

site_description: Wonderful Mobile Documentation
site_author: Wonderful Mobile Project
theme:
  name: readthedocs
nav:
  - Wonderful Kernel: wonderful-kernel/index.md

markdown_extensions:
  - pymdownx.tilde