site_name: Wonderful Mobile Docs
site_url: https://wonderful-mobile-docs.techtransthai.org
repo_url: https://github.com/wonderful-mobile/docs
edit_uri: 'tree/main/docs/'

site_description: Wonderful Mobile Documentation
site_author: Wonderful Mobile Project
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Wonderful Kernel:
      - About: wonderful-kernel/index.md
      - Devices: 
        - Samsung Galaxy A23 5G: wonderful-kernel/samsung-a23xq.md

markdown_extensions:
  - pymdownx.tilde